### PR TITLE
Final demo

### LINKED ISSUE #307: Create Product Demo
As a developer, I'd like to have a video showing the product 

---

### :thought_balloon: &nbsp; Hints & Thoughts
- English, 
- local and normal

### :question: &nbsp; Additional Questions to Answer / Consider

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [x] Should include part that explains the local client
- [x] Should include a part that explains the web app
- [x] Should be added to readme

### PR DESCRIPTION
**Pull request by WolfgangDaniel**
closes #307 

## Changes
Add product demo video to readme and fix bug.

## Checklist before merge

**Developer's responsibilities**
* [ ] **Assign** one or two developers
* [ ] **Change code** if reviewer(s) has/have requested it
* [ ] **Pull request build** has passed
* [ ] **tested locally** (in at least chrome & firefox if frontend)
* [ ] updated the **documentation**
* [ ] added **tests** where necessary

### CODE REVIEW

**Review by SanJSp — CHANGES_REQUESTED** [review]
Hey Daniel, thank you for your Video! I think it perfectly suffices as a product demo and everything important was mentioned. The only thing that bothers me is the embedding of the videos in the readme. I've looked up a way to make it look clean and I've found [this ](https://stackoverflow.com/a/14945782) comment.

If you were to apply this, you could upload the video to youtube (video only accessible via link) and then take a screenshot of the player and the thumbnail. Then you would place this image in the readme as link, which then sends the user to the user page. I think this is a pretty neat solution instead of a two-part split video that is unfortunately not displayed. Maybe you want to consider this 😄 I'd prefer it that way.

**Comment by SanJSp** [comment]
Wow, I really like the look now! Just kidding, now we have a Mocked Youtube Video and by clicking it one is forwarded to the actual youtube video hosted on my channel.

**Review by SanJSp — APPROVED** [review]

**Review by lukashueller — COMMENTED** [review]
I think a very comprehensive video with a good process! Great!

I just believe that we should not use this video for the paper. There we should rather use a screencast, which is overlaid with a voiceover afterward. Then it should be more understandable and less halting. I think that fits then more to the claim of our paper.

Feel free to decide for yourself whether you want to dub the video again now, or if we should do it again for the paper submission.

**Comment by WolfgangDaniel** [comment]
> 
> 
> Wow, I really like the look now! Just kidding, now we have a Mocked Youtube Video and by clicking it one is forwarded to the actual youtube video hosted on my channel.

Thanks Sandro. This is really looking much better now!

**Review by lukashueller — APPROVED** [review]

**Pull request merged**
