### PR TITLE
90 revise architecture

### LINKED ISSUE #90: CONCEPT: Revise architecture
As a development team, we want to define a long-term architecture that we can implement in phases following this issue. The architecture must support the current vision as well as the current planning until the end of the bachelor project.
---

### :thought_balloon: &nbsp; Hints & Thoughts
- How do we proceed with the goal: "Cloud Only"

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [x] Should include an update for the vision-documents (2025 architecture should match 2021 architecture)
- [x] Should include a revision of the architecture (incl. documents in the wiki)
- [x] Should include an easy-to-understand visualization of the architecture that can be used directly in the technical presentation 

**The visualization should include:**
- [ ]  icons for the tools used, 
- [ ] colours for the different areas of `Build` `Manage` `Run`,
- [x] several levels of abstraction 

The visualization should also show which parts of the architecture are already implemented.

### PR DESCRIPTION
**Pull request by lukashueller**
Closes #90
## Changes
As a team, we wanted to agree on a consistent architecture that fit our new project direction.
Please review the following documents:
- README.md -> linked to PR
- Wiki - Architecture: https://github.com/bptlab/ark_automate/wiki/Architecture-in-2021
- Wiki - Vision: https://github.com/bptlab/ark_automate/wiki/Vision-for-2021
- Hackmd: https://hackmd.io/5_gWa_XIQsCAnrioD3v0OA

## Checklist before merge

**Developer's responsibilities**
* [x] **Assign** one or two developers
* [ ] **Change code** if reviewer(s) has/have requested it
* [x] **Pull request build** has passed
* [x] **tested locally** (in at least chrome & firefox if frontend)
* [x] updated the **documentation**
* [x] added **tests** where necessary

### CODE REVIEW

**Review by kej-jay — APPROVED** [review]
grafik
In the vision I do not really understand the point where the code editor is supposed to be the SSoT. Please formulate this more fitting (And if you're already editing the page again, please fix the _implement_ typo in the first line)

**Review by SanJSp — CHANGES_REQUESTED** [review]
Please reference here the web browser in the fmc diagram using the code formatting. f.e. _using his `web-browser`_:
grafik

Same here
grafik

Maybe we should use our bpmw1-intern email for this? You can't send PNs on Github
grafik


Apart from that good work! Looks great and thank you for your effort!

**Comment by lukashueller** [comment]
Hopefully I fixed all your points! Thanks for the detailed review. Could you please check your requested changes and approve the PR? @SanJSp @kej-jay

**Review by MaximilianV — CHANGES_REQUESTED** [review]
I would ask you to remove our internal email-address from the wiki.
a) I'm pretty sure it can only be addressed from internal addresses and is therefore useless for external people.
b) If not, no need for more spam (after all it's a publicly available webpage) ;)
Thanks!

**Comment by lukashueller** [comment]
Hello @MaximilianV,
Thank you for the hint. Have removed it from the referenced document. I should then also remove it from the README and CONTRIBUTING notes under the same aspects, right?

**Comment by MaximilianV** [comment]
> Hello @MaximilianV,
> Thank you for the hint. Have removed it from the referenced document. I should then also remove it from the README and CONTRIBUTING notes under the same aspects, right?

Haven't seen it there, but would be nice, yes. This address is/was rather intended for our internal communication. Thanks!
If you want to offer a way to contact you, maybe create a new address (Gmail, ...) and forward it to your addresses, or offer to create an issue?

**Review by SanJSp — APPROVED** [review]

**Review by MaximilianV — APPROVED** [review]

**Pull request merged**
